#!/bin/bash

DATE=$(date +%Y-%m-%d_%H-%M-%S)
SOURCE_DIR="$HOME/project-data"
BACKUP_DIR="$HOME/backups"
BUCKET_NAME="chinmoy-centos10-backup"
mkdir -p $BACKUP_DIR
tar -czf $BACKUP_DIR/backup_$DATE.tar.gz $SOURCE_DIR
aws s3 cp $BACKUP_DIR/backup_$DATE.tar.gz s3://$BUCKET_NAME/
echo "backup completed successfully" on $DATE
